from src.config.default import _CN as cfg

cfg.ADAMATCHER.MATCH_COARSE.MATCH_TYPE = "dual_softmax"

cfg.TRAINER.CANONICAL_LR = 5e-6
cfg.TRAINER.WARMUP_STEP = 90
cfg.TRAINER.WARMUP_RATIO = 0.1
cfg.TRAINER.MSLR_GAMMA = 0.4

cfg.TRAINER.MSLR_MILESTONES = [4, 7, 9]

# pose estimation
cfg.TRAINER.RANSAC_PIXEL_THR = 0.7

cfg.TRAINER.OPTIMIZER = "adamw"
cfg.TRAINER.ADAMW_DECAY = 0.1
cfg.ADAMATCHER.MATCH_COARSE.TRAIN_COARSE_PERCENT = 0.3
